use quanlybanhang_nkd;
#Bài 1
select hoadon.maHoaDon, hoadon.maKhachHang, hoadon.trangThai, hoadonchitiet.maSanPham, hoadonchitiet.soLuong, hoadon.ngayMuaHang as ngayMua from hoadon, hoadonchitiet where hoadon.maHoaDon=hoadonchitiet.maHoaDon;
select hoadon.maHoaDon, hoadon.maKhachHang, hoadon.trangThai, hoadonchitiet.maSanPham, hoadonchitiet.soLuong, hoadon.ngayMuaHang as ngayMua from hoadon join hoadonchitiet on hoadon.maHoaDon=hoadonchitiet.maHoaDon where hoadon.maKhachHang = 'KH001';
select hoadon.maHoaDon, hoadon.ngayMuaHang as ngayMua, sanpham.tenSP, sanpham.donGia, hoadonchitiet.soLuong, (sanpham.donGia  * hoadonchitiet.soLuong) as thanhTien from hoadon inner join hoadonchitiet on hoadon.maHoaDon=hoadonchitiet.maHoaDon inner join sanpham on sanpham.maSanPham=hoadonchitiet.maSanPham;
select concat(kh.hoVaTenLot, ' ', kh.Ten) as hoVaTenKhach, kh.email, kh.dienThoai, hd.maHoaDon, hd.trangThai AS TrangThaiHoaDon, sum(hdct.soLuong * sp.donGia) as TongTien from khachhang kh join hoadon hd on kh.maKhachHang = hd.maKhachHang join hoadonchitiet hdct on hd.maHoaDon = hdct.maHoaDon join sanpham sp on hdct.maSanPham = sp.maSanPham group by kh.maKhachHang, hd.maHoaDon, kh.hoVaTenLot,kh.Ten, kh.email, kh.dienThoai, hd.trangThai having hd.trangThai ='Chưa thanh toán';
select hd.maHoaDon, hd.ngayMuaHang, sum(hdct.soLuong * sp.donGia) as tongTien from hoadon hd inner join hoadonchitiet hdct on hd.maHoaDon = hdct.maHoaDon inner join sanpham sp on hdct.maSanPham = sp.maSanPham group by hd.maHoaDon, hd.ngayMuaHang having tongTien >= 500000 order by tongTien desc;
#Bài 2
select maKhachHang, hoVaTenLot, Ten, diaChi, Email, dienThoai from khachhang where maKhachHang not in (select distinct maKhachHang from hoadon where ngayMuaHang >= '2016-01-01');
select maSanPham, tenSP from (select sp.maSanPham, sp.tenSP, sum(hdct.soLuong) as tongSoLuong from hoadon hd join hoadonchitiet hdct on hd.maHoaDon = hdct.maHoaDon join sanpham sp on hdct.maSanPham = sp.maSanPham where month(hd.ngayMuaHang) = 12 and year(hd.ngayMuaHang) = 2016 group by sp.maSanPham, sp.tenSP) as LuotMua order by tongSoLuong desc limit 1;
select kh.maKhachHang, concat(kh.hoVaTenLot,' ',kh.Ten) as khachHang,kh.diaChi, kh.Email, kh.dienThoai, sum(hdct.soLuong * sp.donGia) as tongTienMua from hoadon hd join hoadonchitiet hdct on hd.maHoaDon = hdct.maHoaDon join sanpham sp on hdct.maSanPham = sp.maSanPham join khachhang kh on hd.maKhachHang = kh.maKhachHang where year(hd.ngayMuaHang) = 2016 group by kh.maKhachHang, concat(kh.hoVaTenLot,' ',kh.Ten), kh.diaChi, kh.Email, kh.dienThoai order by tongTienMua desc limit 5;
select kh.maKhachHang, concat(hoVaTenLot,' ',Ten)as khacHang, diaChi, Email, dienThoai from khachhang kh join hoadon hd on kh.maKhachHang = hd.maKhachHang join hoadonchitiet hdct on hd.maHoaDon = hdct.maHoaDon join sanpham sp on hdct.maSanPham = sp.maSanPham where kh.diaChi = 'Đà Nẵng' and sp.tenSP = 'Iphone 7 32GB' and month(hd.ngayMuaHang) = 12 and year(hd.ngayMuaHang) = 2016;
select sp.tenSP from SanPham sp join HoaDonChiTiet hdct on sp.maSanPham = hdct.maSanPham group by sp.tenSP having count(hdct.maHoaDon) < (select avg(soLuong) from HoaDonChiTiet);
